export const ROLES_CONSTANT = {
  ADMIN: 'ADMIN',
  SUBADMIN: 'SUBADMIN',
  USER: 'USER',
  MANUFACTURER: 'MANUFACTURER/IMPORTER',
  DISTRIBUTOR: 'DISTRIBUTOR',
  DEALER: 'DEALER',
  APPROVERS: 'APPROVERS',
  RETAILER: 'RETAILER',
};

export const PRIMARY_COLOR = '#B08218';
export const WHITE_COLOR = '#FFFFFF';
