export const ROLES_CONSTANT = {
  ADMIN: 'ADMIN',
  SUBADMIN: 'SUBADMIN',
  USER: 'USER',
  MANUFACTURER: 'MANUFACTURER/IMPORTER',
  DISTRIBUTOR: 'DISTRIBUTOR',
  DEALER: 'DEALER',
  APPROVERS: 'APPROVERS',
  RETAILER: 'RETAILER',
  CONTRACTOR:'CONTRACTOR',
};
export const Banner_Type = {
  PROFILE: 'profilebanner',
  PRODUCT: 'productbanner',
 
};

export const PRIMARY_COLOR = '#B08218';
export const WHITE_COLOR = '#FFFFFF';
